// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  Sample command, kept because it is the smallest thing that exercises the
	 *  whole path: typed argument in, `Result` out, generated binding, typed error.
	 */
	greet: (name: string) => typedError<string, Error>(__TAURI_INVOKE("greet", { name })),
	/**
	 *  Real capability rather than another toy: the frontend is shared across web,
	 *  desktop and mobile, so "which host am I on" is the first thing it actually
	 *  needs from the native side.
	 */
	hostInfo: () => typedError<HostInfo, Error>(__TAURI_INVOKE("host_info")),
	/**
	 *  Opens a URL in the user's real browser rather than inside the webview.
	 * 
	 *  Carries its weight here because it is the one command with a genuine failure
	 *  path on both sides of the boundary: a caller can pass something that is not
	 *  an external URL (their bug, actionable, `InvalidInput`), and the OS handoff
	 *  can fail (not their bug, opaque, `Internal`). Without it the error taxonomy
	 *  would be speculative.
	 */
	openExternal: (url: string) => typedError<null, Error>(__TAURI_INVOKE("open_external", { url })),
};

/* Types */
/**
 *  The single error type every command returns.
 * 
 *  Two things make this worth a module of its own rather than `String`:
 * 
 *  1. It crosses the IPC boundary as a tagged union, so the generated TypeScript
 *     is a discriminated union the frontend can exhaustively `switch` on. A
 *     stringly-typed error would arrive as `unknown` and force the caller to
 *     parse prose.
 *  2. Every variant carries a stable `key`, not a sentence. The Rust side never
 *     decides what the user reads; the frontend maps the key to a translated
 *     message. Putting user-facing English here would make the core
 *     untranslatable and would break the moment the copy changed.
 * 
 *  `detail` is for developers (logs, bug reports) and is never shown as-is.
 */
export type Error = 
/**  The caller sent something this command cannot work with. */
{ kind: "invalidInput"; key: string; detail: string } | 
/**
 *  Anything the caller cannot act on. Deliberately opaque across the
 *  boundary: internal failures leak paths and system detail if forwarded.
 */
{ kind: "internal"; key: string; detail: string };

/**
 *  What the shell knows about the machine it is running on.
 * 
 *  A struct rather than loose return values: adding a field here shows up in
 *  the generated TypeScript as a field, whereas widening a tuple silently
 *  renumbers every call site.
 */
export type HostInfo = {
	/**  `windows`, `macos`, `linux`, `ios` or `android`. */
	os: string,
	/**  `x86_64`, `aarch64`, ... */
	arch: string,
	/**  The shell's own version, so a bug report can name the build. */
	appVersion: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

