import { existsSync, readdirSync, rmSync, statSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

// Reclaims build output. `pnpm clean` runs `cargo clean` first (the Rust target
// dir is by far the biggest thing) and then this, which clears the JS side.
//
// node_modules is deliberately NOT removed: it is reinstall-only, costs a
// network round trip, and is not where the disk goes. Everything here is
// regenerated by a build.
const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");

const TARGETS = [
  "apps/web/dist",
  "apps/web/dev-dist",
  "apps/shell/dist",
  ".turbo",
  "apps/api/.turbo",
  "apps/shell/.turbo",
  "apps/web/.turbo",
  "packages/client/.turbo",
  "packages/config/.turbo",
  "packages/db/.turbo",
  "packages/types/.turbo",
];

// Recursive, because directory size is the number worth reporting and a stat on
// a directory reports the entry rather than its contents.
function sizeOf(path) {
  const stat = statSync(path, { throwIfNoEntry: false });
  if (!stat) return 0;
  if (!stat.isDirectory()) return stat.size;
  let total = 0;
  for (const entry of readdirSync(path)) total += sizeOf(join(path, entry));
  return total;
}

let freed = 0;
for (const rel of TARGETS) {
  const path = join(repoRoot, rel);
  if (!existsSync(path)) continue;
  freed += sizeOf(path);
  rmSync(path, { recursive: true, force: true });
  console.log(`  removed ${rel}`);
}

console.log(`\n  freed ${(freed / 1024 / 1024).toFixed(1)} MB of JS build output`);
console.log("  (the Rust target dir was cleared by the cargo clean that ran first)\n");
